# Generated by Django 3.0.3 on 2020-02-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals_app.Service'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professionals_app.UserType'),
        ),
    ]
