# Generated by Django 3.0.3 on 2020-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0008_auto_20200302_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rviewer_lname',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_lname',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_fname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
