# Generated by Django 3.0.3 on 2020-03-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0013_auto_20200303_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
