# Generated by Django 3.0.3 on 2020-03-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0016_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professionals_app.Service'),
        ),
    ]
