# Generated by Django 3.0.3 on 2020-03-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0018_auto_20200305_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='complaint',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
