# Generated by Django 3.0.3 on 2020-03-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0019_report_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='complaint',
            field=models.CharField(max_length=500),
        ),
    ]
