# Generated by Django 3.0.3 on 2020-03-05 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipanampesaonline',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='checkout_request_id',
            field=models.CharField(default='h', max_length=50),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='merchant_request_id',
            field=models.CharField(default='h', max_length=70),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='mpesa_receipt_number',
            field=models.CharField(default='h', max_length=30),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='mpesa_transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 19, 43, 10, 879495)),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='phone_number',
            field=models.CharField(default='h', max_length=15),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='result_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lipanampesaonline',
            name='result_description',
            field=models.CharField(default='h', max_length=120),
        ),
    ]
