# Generated by Django 3.0.3 on 2020-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0004_c2bpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2bpayments',
            name='BillRefNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='BusinessShortCode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='FirstName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='LastName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='MSISDN',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='OrgAccountBalance',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='TransAmount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='TransID',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='TransTime',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='c2bpayments',
            name='TransactionType',
            field=models.CharField(max_length=20),
        ),
    ]
