# Generated by Django 3.0.3 on 2020-03-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0005_auto_20200309_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C2BPayments',
            new_name='C2BPayment',
        ),
    ]
