# Generated by Django 3.0.3 on 2020-02-21 04:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_pictures/%y/%m/%d'),
        ),
    ]
