# Generated by Django 3.0.3 on 2020-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0003_auto_20200221_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='searches',
            field=models.IntegerField(blank=True),
        ),
    ]
