# Generated by Django 3.0.3 on 2020-02-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0003_auto_20200224_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default='JKUAT', max_length=25),
        ),
    ]
