# Generated by Django 3.0.3 on 2020-02-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0004_auto_20200221_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='searches',
            field=models.IntegerField(default=0),
        ),
    ]
