# Generated by Django 3.0.3 on 2020-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0005_auto_20200224_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.EmailField(default='mchemweno27@gmail.com', max_length=25),
        ),
    ]
