# Generated by Django 3.0.3 on 2020-03-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0007_auto_20200224_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_fname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rviewer_lname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
