# Generated by Django 3.0.3 on 2020-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0011_auto_20200303_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
