# Generated by Django 3.0.3 on 2020-03-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals_app', '0012_auto_20200303_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='professionals_app.Service'),
        ),
    ]
